export interface ICar {
    id: string,
    // car: string,
    // car_model: string,
    // car_color: string,
    // car_model_year: number,
    model_vin?: string,
    model_color?: string,
    model_mileage?: number,
    // price: string,
    // availability: boolean
    model_id: number,
    model_make_id: string,
    model_name: string,
    model_trim: string,
    model_year: number,
    model_body: string,
    model_engine_position: string,
    model_engine_cc: number,
    model_engine_cyl: number,
    model_engine_type: string,
    model_engine_valves_per_cyl: number,
    model_engine_power_ps: number,
    model_engine_power_rpm:number,
    model_engine_torque_nm: number,
    model_engine_torque_rpm:number,
    model_engine_bore_mm:number,
    model_engine_stroke_mm:number,
    model_engine_compression: number,
    model_engine_fuel: string,
    model_top_speed_kph:number,
    model_0_to_100_kph:number,
    model_drive: string,
    model_transmission_type: string,
    model_seats:number,
    model_doors: number,
    model_weight_kg: number,
    model_length_mm:number,
    model_width_mm:number,
    model_height_mm:number,
    model_wheelbase_mm:number,
    model_lkm_hwy: number,
    model_lkm_mixed: number,
    model_lkm_city: number,
    model_fuel_cap_l: number,
    model_sold_in_us: number,
    model_co2:number,
    make_country: string,
    [key: string]: string | number | undefined; 
}

export interface IBrand {
    id: string,
    brandName: string,
    modelList : string[],
    [key: string]: string | string[] | undefined; 
}