export interface ICar {
    // id: number,
    // car: string,
    // car_model: string,
    // car_color: string,
    // car_model_year: number,
    // car_vin: string,
    // price: string,
    // availability: boolean
    model_id:"82563",
    model_make_id:"Acura",
    model_name:"ILX",
    model_trim:"4dr Sedan (2.0L 4cyl 5A)",
    model_year:"2022",
    model_body:"Compact Cars",
    model_engine_position:"Front",
    model_engine_cc:"2000",
    model_engine_cyl:"4",
    model_engine_type:"Inline",
    model_engine_valves_per_cyl:"4",
    model_engine_power_ps:"150",
    model_engine_power_rpm:null,
    model_engine_torque_nm:"140",
    model_engine_torque_rpm:null,
    model_engine_bore_mm:null,
    model_engine_stroke_mm:null,
    model_engine_compression:"10.6",
    model_engine_fuel:"Premium Unleaded (Required)",
    model_top_speed_kph:null,
    model_0_to_100_kph:null,
    model_drive:"Front Wheel Driv",
    model_transmission_type:"Automatic",
    model_seats:null,
    model_doors:"4",
    model_weight_kg:"2955",
    model_length_mm:null,
    model_width_mm:null,
    model_height_mm:null,
    model_wheelbase_mm:null,
    model_lkm_hwy:"35.0",
    model_lkm_mixed:"28.0",
    model_lkm_city:"24.0",
    model_fuel_cap_l:"13",
    model_sold_in_us:"1",
    model_co2:null,
    model_make_display:"Acura",
    make_display:"Acura",
    make_country:"USA"
}